### ISSUE TITLE
NEBNext® Multiplex Oligos for Illumina® (96 Unique Dual Index Primer Pairs)

### ISSUE THREAD

**Issue by xlinxlin** [angelovangel/samplesheet-generator#1]
Links:https://international.neb.com/products/e6440-nebnext-multiplex-oligos-for-illumina-96-unique-dual-index-primer-pairs#Protocols,%20Manuals%20&%20Usage_Usage%20Guidelines

[E6440_NovaSeq_SampleSheet.txt](https://github.com/angelovangel/samplesheet-generator/files/5327235/E6440_NovaSeq_SampleSheet.txt)

**Comment by angelovangel** [comment]
Probably wrong well/sequence assignments in sample sheet.
